version: "3.7"

services:
  app:
    container_name: client-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true    

# networks:
#   default:
#     external:
#       name: server_bpcl-net
