export interface IIndustryType {
  value: string;
  label: string;
}

interface IBusinessToIndustryMap {
  [key: string]: IIndustryType[];
}
export const businessToIndustryMap: IBusinessToIndustryMap = {
  "1": [
    { value: "1.1", label: "Cement & Construction Material" },
    { value: "1.2", label: "Mining, Infra & Construction" },
    { value: "1.3", label: "Steel & Iron" },
    { value: "1.4", label: "Marble & Stone" },
    { value: "1.5", label: "Stone Crusher" },
    { value: "1.6", label: "Borewell" },
    { value: "1.7", label: "Coal Transport" },
    { value: "1.8", label: "Minerals" },
    { value: "1.9", label: "Earth Movers" },
  ],
  "2": [
    { value: "2.1", label: "Petroleum Products - LPG" },
    { value: "2.2", label: "Petroleum PCVO" },
    { value: "2.3", label: "Chemical Petroleum Products" },
    { value: "2.4", label: "Bitumin Transporter" },
    { value: "2.5", label: "Industrial Gas" },
    { value: "2.6", label: "Polymers" },
    { value: "2.7", label: "PCVO - LPG" },
    { value: "2.8", label: "Plastic Products" },
    { value: "2.9", label: "Lube PCVO" },
    { value: "2.10", label: "Paint" },
  ],
  "3": [
    { value: "3.1", label: "Perishable Goods - Fruits & Vegetables" },
    { value: "3.2", label: "Cold Storage - Food Items" },
    { value: "3.3", label: "Bulk Edible Oil" },
    { value: "3.4", label: "Textiles" },
    { value: "3.5", label: "Food Grain" },
    { value: "3.6", label: "Milk & Dairy Products" },
    { value: "3.7", label: "Ceramic" },
    { value: "3.8", label: "Spices" },
    { value: "3.9", label: "Fisheries" },
    { value: "3.10", label: "Wood & Furniture" },
    { value: "3.11", label: "Food/Bevarages/FMCG" },
    { value: "3.12", label: "Electronics & Electricals" },
    { value: "3.13", label: "Poultry & Meat" },
    { value: "3.14", label: "Water Supplier" },
    { value: "3.15", label: "Waste Management" },
    { value: "3.16", label: "Liquor & Wine" },
    { value: "3.17", label: "Paper Products" },
    { value: "3.18", label: "Brass Goods - Export" },
    { value: "3.19", label: "Tobaco" },
    { value: "3.20", label: "Glass" },
    { value: "3.21", label: "Carpet Trasport" },
    { value: "3.22", label: "Mineral Water" },
    { value: "3.23", label: "Leather" },
    { value: "3.24", label: "Cattle Movement" },
    { value: "3.25", label: "Ice" },
    { value: "3.26", label: "Cosmetics" },
  ],
  "4": [
    { value: "4.1", label: "Ambulance Services" },
    { value: "4.2", label: "Medicines" },
    { value: "4.3", label: "Medical Equipments" },
  ],
  "5": [
    { value: "5.1", label: "Tyre Transport" },
    { value: "5.2", label: "Machinery & Parts" },
    { value: "5.3", label: "Automotive & Vehical Carriers" },
    { value: "5.4", label: "Railway Contract" },
    { value: "5.5", label: "Industrial Equipment" },
    { value: "5.6", label: "Industrial Explosives/Crackers/Matchbox" },
    { value: "5.7", label: "Brolier" },
    { value: "5.8", label: "Cryogenics Material" },
  ],
  "6": [
    { value: "6.1", label: "Telecom" },
    { value: "6.2", label: "DG Operator" },
    { value: "6.3", label: "Shipper & Forwarder" },
    { value: "6.4", label: "Educational Institutions" },
    { value: "6.5", label: "Reliance Products" },
    { value: "6.6", label: "Retail Stores" },
    { value: "6.7", label: "Finance Company" },
    { value: "6.8", label: "Advertisement Vehicles" },
    { value: "6.9", label: "E -Commerce" },
  ],
  "7": [
    { value: "7.1", label: "Travels & Passanger Vehicles" },
    { value: "7.2", label: "Parcel & Courier" },
    { value: "7.3", label: "Defence and Security Services" },
    { value: "7.4", label: "Courier Services" },
    { value: "7.5", label: "ATM Cash Filling Vans" },
    { value: "7.6", label: "Airline Services" },
    { value: "7.7", label: "Crane Services" },
    { value: "7.8", label: "Government Services" },
    { value: "7.9", label: "Hospitality" },
    { value: "7.10", label: "Waste Management" },
    { value: "7.11", label: "Health Services" },
    { value: "7.12", label: "Breakdown Services" },
    { value: "7.13", label: "Warehousing" },
    { value: "7.14", label: "Emergency Services" },
    { value: "7.15", label: "Laundry" },
    { value: "7.16", label: "News Paper" },
    { value: "7.17", label: "Water Park" },
  ],
  "8": [
    { value: "8.1", label: "Export & Import Containers" },
    { value: "8.2", label: "Agricultural Products" },
    { value: "8.3", label: "Pest Control" },
    { value: "8.4", label: "Coir Transport" },
    { value: "8.5", label: "Animal Foods" },
    { value: "8.6", label: "Diamond Product Transport" },
    { value: "8.7", label: "Cattle Movement" },
    { value: "8.8", label: "Type Your Own Business Type" },
  ],
};
