//Assisted flow related actions
export const SET_ASSISTED_FLOW = "SET_ASSISTED_FLOW";
export const UNSET_ASSISTED_FLOW = "UNSET_ASSISTED_FLOW";
export const ASSIGN_ASSISTED_CUSTOMER_USER = "ASSIGN_ASSISTED_CUSTOMER_USER";

//set Language
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_BUSINESS = "SET_BUSINESS";
export const SET_BUSINESS_PROGRAM = "SET_BUSINESS_PROGRAM";
export const SERVER_TOKEN = "SERVER_TOKEN";
export const USER_TOKEN = "USER_TOKEN";

//User login
export const ASSIGN_USERNAME = "ASSIGN_USERNAME";
export const ASSIGN_ROLE = "ASSIGN_ROLE";
export const ASSIGN_PASSWORD = false;
export const LOG_USER_IN = "LOG_USER_IN";
export const LOG_USER_OUT = "LOG_USER_OUT";
export const RESET = "RESET";



export const SMARTFLEET_PRIMARY_MOBILE_NUMBER = "SMARTFLEET_PRIMARY_MOBILE_NUMBER";
// export const PAYMENT_ISPAYMENTAPPLICABLE = "PAYMENT_ISPAYMENTAPPLICABLE";
export const SET_LOADER = "SET_LOADER";
export const SET_SMARTFLEET_APPLICATION_NUMBER = "SET_SMARTFLEET_APPLICATION_NUMBER";
export const SET_SMARTFLEET_PAYMENT_METHOD = "SET_SMARTFLEET_PAYMENT_METHOD";

//payment section Enable/Disable
export const SET_PAYMENTSECTON_FAID = "SET_PAYMENTSECTON_FAID";
export const SET_PAYMENTSECTON_INDIVIDUAL = "SET_PAYMENTSECTON_INDIVIDUAL";
export const SET_PAYMENTSECTON_BULKUPLOAD = "SET_PAYMENTSECTON_BULKUPLOAD";

// card management bulk action
export const SET_CARDS_FOR_BULK_ACTION = "SET_CARDS_FOR_BULK_ACTION";

// Popup bulk action
export const SET_POPUP_TITLE_FOR_BULK_ACTION = "SET_POPUP_TITLE_FOR_BULK_ACTION";
export const SET_POPUP_DESCRIPTION_FOR_BULK_ACTION = "SET_POPUP_DESCRIPTION_FOR_BULK_ACTION";
export const SET_POPUP_ACTION_TYPE_FOR_BULK_ACTION = "SET_POPUP_ACTION_TYPE_FOR_BULK_ACTION";
